### ISSUE TITLE
最新版的axum和config API已经修改

### ISSUE THREAD

**Issue by nomaka** [axumrs/todo#1]
这个repo中使用的都是老版本的axum和config：

在最新版的config中已经使用config::Config::builder代替cfg.merge
在最新版的axum中IntoResponse用法也与老版本不同

**Comment by axumrs** [comment]
每个框架都在不停的迭代，我们没可能也没精力做到所有专题的源代码都紧跟最新的框架，为此我们一开始就专门建立了一个专题，用于收集整理专题中用到的框架、CRATE的重大变化。请移步 https://axum.rs/subject/diff 专题。

**Comment by axumrs** [comment]
我们的写作原则是：

- 新创建一个专题时，我们会使用框架和相关crate的最新版本。

- 对于已创建的专题，我们不会直接更新专题的依赖和代码，而是采用集中上文所述的，专门用于收集整理版本差异的方式进行说明。
